### ISSUE TITLE
1.19.4 support?

### ISSUE THREAD

**Issue by ninjakitty844** [lichenaut/PlantNerfer#6]
PlantNerfer does not work on 1.19.4, and I can't update my server past 1.19.4 (mainly because of some crucial plugins that didn't update and likely won't update).

Would it be possible to update PlantNerfer to add 1.19.4 support? If not, that's ok, but it means I have to use the original plugin that PlantNerfer was based on and I think PlantNerfer is better in many ways.

**Comment by lichenaut** [comment]
Hey, I'll look into this once my finals season is over. If you can't wait, it most likely wouldn't be too hard to change the version yourself and rebuild the project.

**Comment by ninjakitty844** [comment]
Many thanks :]

I wouldn't say it's too urgent, good luck with your finals!

**Comment by lichenaut** [comment]
Hey, I changed the version numbers to 1.19.4, but did not test it on a 1.19 server. Let me know if there's a problem.

https://github.com/lichenaut/PlantNerfer/releases/tag/special-version

**Comment by ninjakitty844** [comment]
Hi, I tried it out just now. It won't load but it gave me some errors:

[01:12:26 ERROR]: Fatal error trying to convert PlantNerfer v1.6.1:com/lichenaut/plantnerfer/Main.class
java.lang.IllegalArgumentException: Unsupported class file major version 65
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:199) ~[asm-9.4.jar:9.4]
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:180) ~[asm-9.4.jar:9.4]
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166) ~[asm-9.4.jar:9.4]
        at org.bukkit.craftbukkit.v1_19_R3.util.Commodore.convert(Commodore.java:171) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at org.bukkit.craftbukkit.v1_19_R3.util.CraftMagicNumbers.processClass(CraftMagicNumbers.java:405) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:209) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:157) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:152) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:534) ~[?:?]
        at java.lang.Class.forName(Class.java:513) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.loadPlugins(CraftServer.java:445) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1120) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[01:12:26 WARN]: Legacy plugin MendingTradeNerf v1.0.1 does not specify an api-version.

[01:12:39 INFO]: [PlantNerfer] Enabling PlantNerfer v1.6.1
[01:12:39 ERROR]: Fatal error trying to convert PlantNerfer v1.6.1:com/lichenaut/plantnerfer/util/VersionGetter.class
java.lang.IllegalArgumentException: Unsupported class file major version 65
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:199) ~[asm-9.4.jar:9.4]
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:180) ~[asm-9.4.jar:9.4]
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166) ~[asm-9.4.jar:9.4]
        at org.bukkit.craftbukkit.v1_19_R3.util.Commodore.convert(Commodore.java:171) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at org.bukkit.craftbukkit.v1_19_R3.util.CraftMagicNumbers.processClass(CraftMagicNumbers.java:405) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:209) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:157) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:152) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at com.lichenaut.plantnerfer.Main.onEnable(Main.java:52) ~[PlantNerfer.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:577) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:488) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:643) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:442) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1120) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[01:12:39 ERROR]: [PlantNerfer] Minecraft version under 1.20 detected! Disabling plugin.

**Comment by lichenaut** [comment]
I have made some changes, and have gotten it to load on a 1.19.4 Purpur server. The download will be at the same location I previously linked. I'm sorry for quickly doing it the first time around. Let me know if it still does not work.

**Comment by ninjakitty844** [comment]
> I have made some changes, and have gotten it to load on a 1.19.4 Purpur server. The download will be at the same location I previously linked. I'm sorry for quickly doing it the first time around. Let me know if it still does not work.

Hi, sorry it's been a while. I guess in my mind mentally I marked it as fixed without actually trying it out. But when I went to use it just now, I found that there are issues. Currently the plugin loads, and generates a config, but it doesn't do anything. When I use the example config for oak sapling from the wiki, that doesn't change how oak saplings grow at all. And when I run the reload command, there is no output.

**Comment by lichenaut** [comment]
Hello again, at the same link I posted earlier, I have uploaded a new version, where, in 1.19.4, I have been able to make changes to the config and reload the plugin (ex. can-place), and see those changes reflected in-game. Also, the commands do not show feedback if a player does not have permission to use them.

**Comment by ninjakitty844** [comment]
In the latest version at that link, I am still unable to see any changes reflected in-game, including `can-place`. The `/pn help` command isn't doing anything. The growth rates aren't being affected. No console output whatsoever aside from `[PlantNerfer] Enabling PlantNerfer v1.6.0`.

I'm not sure how or why, but it seems like the plugin tries to enable but never starts running any code...?

**Comment by lichenaut** [comment]
That's odd, please: check if the plugin becomes disabled, test the Oak Sapling without any world or biome-related settings, as that may make the behavior more unclear, and make sure you have `op` if you're using the `pn` command as a player.

**Comment by ninjakitty844** [comment]
I've had OP this whole time, the commands still just never give any output in chat or in console.

With a completely default config, and just `can-place` set to false for oak sapling (in all biome groups, so it does not say canplace = true anywhere in any config), I can still plant oak sapling.

The logs do not say that PlantNerfer is disabled, and when I run `/plugins` it's name in the plugin list is green, whereas a disabled plugin would be red I think.

**Comment by ninjakitty844** [comment]
[PlantNerfer.zip](https://github.com/user-attachments/files/19195822/PlantNerfer.zip)
Here is my config folder if it helps. It is completely unchanged from default aside from me setting `can-place` to false for oak sapling in both presets.yml and config.yml

**Comment by lichenaut** [comment]
You're right that disabled plugins show up red. I noticed that your `locales` directory in the `PlantNerfer` directory is empty.

I set up a new, vanilla, 1.19.4 server with your directory and the special version I wrote, and everything worked as expected. Maybe you're running a fork of spigot that isn't compatible, or another plugin or configuration is preventing this plugin from working. I noticed that the locales directory was correctly filled with locales once I ran your configuration. My Discord username is the same as my GitHub username, in case you need more help.
